# 微信
wechat:
  appId: xxxxxxxxxxxxxx
  appSecret: xxxxxxxxxxxx
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  openIdUrl: https://api.weixin.qq.com/sns/jscode2session
  phoneUrl: https://api.weixin.qq.com/wxa/business/getuserphonenumber?access_token={0}
  # 微信支付参数信息
  pay:
    mchId: 
    key: 
    # 微信支付URL
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    # 微信退款URL
    refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
    # 微信提现URL
    transfersUrl: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
    # 证书路径
    certificatePath: apiclient_cert.p12
    # 回调地址
    callback:
      domainUrl: https://api.zghyhl.cn/love-service

# 助通科技 短信
zt:
  userName: 
  passWord: 
  signature: 
  signID: 
  templateID: 
  url:
    template: https://api.mix2.zthysms.com/v2/sendSmsTp