-- 同步 brt_sales_order / brt_sales_order_details 字段以对接 client_order 与 order_items 数据

-- brt_sales_order 新字段
ALTER TABLE `brt_sales_order`
    ADD COLUMN `order_sn` varchar(64) DEFAULT NULL COMMENT '来源系统订单编号',
    ADD COLUMN `client_id` varchar(64) DEFAULT NULL COMMENT '来源系统客户ID',
    ADD COLUMN `consignee` varchar(128) DEFAULT NULL COMMENT '收货人',
    ADD COLUMN `address` varchar(255) DEFAULT NULL COMMENT '收货地址',
    ADD COLUMN `tel` varchar(32) DEFAULT NULL COMMENT '收货电话',
    ADD COLUMN `order_amount` decimal(18,2) DEFAULT NULL COMMENT '订单金额',
    ADD COLUMN `shipping_fee` decimal(18,2) DEFAULT NULL COMMENT '运费',
    ADD COLUMN `money_paid` decimal(18,2) DEFAULT NULL COMMENT '已付金额',
    ADD COLUMN `discount` decimal(18,2) DEFAULT NULL COMMENT '优惠金额',
    ADD COLUMN `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
    ADD COLUMN `manufacturer_id` varchar(64) DEFAULT NULL COMMENT '生产方ID',
    ADD COLUMN `delivery_date` date DEFAULT NULL COMMENT '交货日期',
    ADD COLUMN `mes` varchar(16) DEFAULT NULL COMMENT '是否由MES创建',
    ADD COLUMN `mes_time` datetime DEFAULT NULL COMMENT 'MES创建时间',
    ADD COLUMN `logistic_code` varchar(128) DEFAULT NULL COMMENT '物流单号',
    ADD COLUMN `is_withdraw` varchar(8) DEFAULT NULL COMMENT '是否撤回',
    ADD COLUMN `user_code` varchar(64) DEFAULT NULL COMMENT '账号编码',
    ADD COLUMN `user_org_code` varchar(64) DEFAULT NULL COMMENT '账号组织编码',
    ADD COLUMN `transfer_status` varchar(8) DEFAULT NULL COMMENT '转移状态',
    ADD COLUMN `snapshot` text COMMENT '来源快照',
    ADD COLUMN `transfer_from` varchar(64) DEFAULT NULL COMMENT '转移来源',
    ADD COLUMN `settle_order_amount` decimal(18,2) DEFAULT NULL COMMENT '结算金额',
    ADD COLUMN `type` varchar(8) DEFAULT NULL COMMENT '订单类型',
    ADD COLUMN `out_order_no` varchar(64) DEFAULT NULL COMMENT '外部订单号';

-- brt_sales_order_details 新字段
ALTER TABLE `brt_sales_order_details`
    ADD COLUMN `prod_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
    ADD COLUMN `prod_code` varchar(64) DEFAULT NULL COMMENT '产品编码',
    ADD COLUMN `prod_type` int DEFAULT NULL COMMENT '产品类型',
    ADD COLUMN `component` text COMMENT '产品组成',
    ADD COLUMN `width` decimal(10,2) DEFAULT NULL COMMENT '宽度',
    ADD COLUMN `height` decimal(10,2) DEFAULT NULL COMMENT '高度',
    ADD COLUMN `thickness` decimal(10,2) DEFAULT NULL COMMENT '厚度',
    ADD COLUMN `weight` decimal(10,2) DEFAULT NULL COMMENT '重量',
    ADD COLUMN `procs_desc` text COMMENT '工艺描述',
    ADD COLUMN `procs_attachpath` text COMMENT '工艺附件',
    ADD COLUMN `item_number` int DEFAULT NULL COMMENT '件数',
    ADD COLUMN `item_price` decimal(18,2) DEFAULT NULL COMMENT '单价',
    ADD COLUMN `actual_amount` decimal(18,2) DEFAULT NULL COMMENT '实际金额',
    ADD COLUMN `delivery_sn` varchar(128) DEFAULT NULL COMMENT '发货单号',
    ADD COLUMN `delivery_id` varchar(64) DEFAULT NULL COMMENT '发货ID',
    ADD COLUMN `item_status` int DEFAULT NULL COMMENT '明细状态',
    ADD COLUMN `shipping_time` datetime DEFAULT NULL COMMENT '发货时间',
    ADD COLUMN `shipping_status` int DEFAULT NULL COMMENT '物流状态',
    ADD COLUMN `prod_description` text COMMENT '产品描述',
    ADD COLUMN `imagefile_path` text COMMENT '原始文件路径',
    ADD COLUMN `comments` text COMMENT '客户备注',
    ADD COLUMN `preview_image_path` text COMMENT '预览图',
    ADD COLUMN `thumbnails_path` text COMMENT '缩略图',
    ADD COLUMN `proc_code` varchar(255) DEFAULT NULL COMMENT '工艺编码集合',
    ADD COLUMN `item_seq` int DEFAULT NULL COMMENT '明细排序',
    ADD COLUMN `orderItem_sn` varchar(128) DEFAULT NULL COMMENT '明细流水号',
    ADD COLUMN `is_urgent` tinyint DEFAULT NULL COMMENT '是否加急',
    ADD COLUMN `delivery_date` date DEFAULT NULL COMMENT '发货日期',
    ADD COLUMN `logistics_type` varchar(64) DEFAULT NULL COMMENT '物流类型',
    ADD COLUMN `mat_cost` decimal(18,2) DEFAULT NULL COMMENT '物料成本',
    ADD COLUMN `proc_cost` decimal(18,2) DEFAULT NULL COMMENT '工艺成本',
    ADD COLUMN `gross_margin` decimal(18,2) DEFAULT NULL COMMENT '毛利',
    ADD COLUMN `tax_fee` decimal(18,2) DEFAULT NULL COMMENT '税费',
    ADD COLUMN `color_format` varchar(64) DEFAULT NULL COMMENT '色彩模式',
    ADD COLUMN `prod_attrs` text COMMENT '产品属性',
    ADD COLUMN `snapshot` text COMMENT '来源快照';
