-- 同步 brt_sales_order / brt_sales_order_details 字段以对接 client_order 与 order_items 数据

-- brt_sales_order 新字段
ALTER TABLE `brt_sales_order`
    ADD COLUMN `order_sn` varchar(64) DEFAULT NULL COMMENT '来源系统订单编号',
    ADD COLUMN `client_id` varchar(64) DEFAULT NULL COMMENT '来源系统客户ID',
    ADD COLUMN `consignee` varchar(128) DEFAULT NULL COMMENT '收货人',
    ADD COLUMN `address` varchar(255) DEFAULT NULL COMMENT '收货地址',
    ADD COLUMN `tel` varchar(32) DEFAULT NULL COMMENT '收货电话',
    ADD COLUMN `order_amount` decimal(18,2) DEFAULT NULL COMMENT '订单金额',
    ADD COLUMN `shipping_fee` decimal(18,2) DEFAULT NULL COMMENT '运费',
    ADD COLUMN `money_paid` decimal(18,2) DEFAULT NULL COMMENT '已付金额',
    ADD COLUMN `discount` decimal(18,2) DEFAULT NULL COMMENT '优惠金额',
    ADD COLUMN `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
    ADD COLUMN `manufacturer_id` varchar(64) DEFAULT NULL COMMENT '生产方ID',
    ADD COLUMN `delivery_date` date DEFAULT NULL COMMENT '交货日期',
    ADD COLUMN `mes` varchar(16) DEFAULT NULL COMMENT '是否由MES创建',
    ADD COLUMN `mes_time` datetime DEFAULT NULL COMMENT 'MES创建时间',
    ADD COLUMN `logistic_code` varchar(128) DEFAULT NULL COMMENT '物流单号',
    ADD COLUMN `is_withdraw` varchar(8) DEFAULT NULL COMMENT '是否撤回',
    ADD COLUMN `user_code` varchar(64) DEFAULT NULL COMMENT '账号编码',
    ADD COLUMN `user_org_code` varchar(64) DEFAULT NULL COMMENT '账号组织编码',
    ADD COLUMN `transfer_status` varchar(8) DEFAULT NULL COMMENT '转移状态',
    ADD COLUMN `snapshot` text COMMENT '来源快照',
    ADD COLUMN `transfer_from` varchar(64) DEFAULT NULL COMMENT '转移来源',
    ADD COLUMN `settle_order_amount` decimal(18,2) DEFAULT NULL COMMENT '结算金额',
    ADD COLUMN `type` varchar(8) DEFAULT NULL COMMENT '订单类型',
    ADD COLUMN `out_order_no` varchar(64) DEFAULT NULL COMMENT '外部订单号';

-- brt_sales_order_details 新字段
ALTER TABLE `brt_sales_order_details`
    ADD COLUMN `prod_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
    ADD COLUMN `prod_code` varchar(64) DEFAULT NULL COMMENT '产品编码',
    ADD COLUMN `prod_type` int DEFAULT NULL COMMENT '产品类型',
    ADD COLUMN `component` text COMMENT '产品组成',
    ADD COLUMN `width` decimal(10,2) DEFAULT NULL COMMENT '宽度',
    ADD COLUMN `height` decimal(10,2) DEFAULT NULL COMMENT '高度',
    ADD COLUMN `thickness` decimal(10,2) DEFAULT NULL COMMENT '厚度',
    ADD COLUMN `weight` decimal(10,2) DEFAULT NULL COMMENT '重量',
    ADD COLUMN `procs_desc` text COMMENT '工艺描述',
    ADD COLUMN `procs_attachpath` text COMMENT '工艺附件',
    ADD COLUMN `item_number` int DEFAULT NULL COMMENT '件数',
    ADD COLUMN `item_price` decimal(18,2) DEFAULT NULL COMMENT '单价',
    ADD COLUMN `actual_amount` decimal(18,2) DEFAULT NULL COMMENT '实际金额',
    ADD COLUMN `delivery_sn` varchar(128) DEFAULT NULL COMMENT '发货单号',
    ADD COLUMN `delivery_id` varchar(64) DEFAULT NULL COMMENT '发货ID',
    ADD COLUMN `item_status` int DEFAULT NULL COMMENT '明细状态',
    ADD COLUMN `shipping_time` datetime DEFAULT NULL COMMENT '发货时间',
    ADD COLUMN `shipping_status` int DEFAULT NULL COMMENT '物流状态',
    ADD COLUMN `prod_description` text COMMENT '产品描述',
    ADD COLUMN `imagefile_path` text COMMENT '原始文件路径',
    ADD COLUMN `comments` text COMMENT '客户备注',
    ADD COLUMN `preview_image_path` text COMMENT '预览图',
    ADD COLUMN `thumbnails_path` text COMMENT '缩略图',
    ADD COLUMN `proc_code` varchar(255) DEFAULT NULL COMMENT '工艺编码集合',
    ADD COLUMN `item_seq` int DEFAULT NULL COMMENT '明细排序',
    ADD COLUMN `orderItem_sn` varchar(128) DEFAULT NULL COMMENT '明细流水号',
    ADD COLUMN `is_urgent` tinyint DEFAULT NULL COMMENT '是否加急',
    ADD COLUMN `delivery_date` date DEFAULT NULL COMMENT '发货日期',
    ADD COLUMN `logistics_type` varchar(64) DEFAULT NULL COMMENT '物流类型',
    ADD COLUMN `mat_cost` decimal(18,2) DEFAULT NULL COMMENT '物料成本',
    ADD COLUMN `proc_cost` decimal(18,2) DEFAULT NULL COMMENT '工艺成本',
    ADD COLUMN `gross_margin` decimal(18,2) DEFAULT NULL COMMENT '毛利',
    ADD COLUMN `tax_fee` decimal(18,2) DEFAULT NULL COMMENT '税费',
    ADD COLUMN `color_format` varchar(64) DEFAULT NULL COMMENT '色彩模式',
    ADD COLUMN `prod_attrs` text COMMENT '产品属性',
    ADD COLUMN `snapshot` text COMMENT '来源快照';

-- brt_sales_order_items 订单明细表（拆分 brt_sales_order_details 的订单明细信息）
CREATE TABLE IF NOT EXISTS `brt_sales_order_items` (
    `id` bigint NOT NULL COMMENT '来源明细ID',
    `order_id` varchar(64) NOT NULL COMMENT '销售订单ID',
    `prod_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
    `prod_code` varchar(64) DEFAULT NULL COMMENT '产品编码',
    `prod_type` int DEFAULT NULL COMMENT '产品类型',
    `component` longtext COMMENT '组件信息(JSON)',
    `width` decimal(10,2) DEFAULT NULL COMMENT '宽度',
    `height` decimal(10,2) DEFAULT NULL COMMENT '高度',
    `thickness` decimal(10,2) DEFAULT NULL COMMENT '厚度',
    `weight` decimal(10,2) DEFAULT NULL COMMENT '重量',
    `procs_desc` longtext COMMENT '工艺描述',
    `procs_attachpath` longtext COMMENT '工艺附件',
    `item_number` decimal(18,2) DEFAULT NULL COMMENT '件数',
    `item_price` decimal(18,2) DEFAULT NULL COMMENT '单价',
    `actual_amount` decimal(18,2) DEFAULT NULL COMMENT '实际金额',
    `delivery_sn` varchar(128) DEFAULT NULL COMMENT '发货单号',
    `delivery_id` varchar(64) DEFAULT NULL COMMENT '发货ID',
    `item_status` int DEFAULT NULL COMMENT '明细状态',
    `shipping_time` datetime DEFAULT NULL COMMENT '发货时间',
    `shipping_status` int DEFAULT NULL COMMENT '物流状态',
    `prod_description` longtext COMMENT '产品描述',
    `imagefile_path` longtext COMMENT '原始文件路径',
    `comments` longtext COMMENT '客户备注',
    `preview_image_path` longtext COMMENT '预览图',
    `thumbnails_path` longtext COMMENT '缩略图',
    `proc_code` varchar(255) DEFAULT NULL COMMENT '工艺编码集合',
    `item_seq` int DEFAULT NULL COMMENT '明细排序',
    `orderItem_sn` varchar(128) DEFAULT NULL COMMENT '明细流水号',
    `is_urgent` tinyint DEFAULT NULL COMMENT '是否加急',
    `delivery_date` date DEFAULT NULL COMMENT '发货日期',
    `logistics_type` varchar(64) DEFAULT NULL COMMENT '物流类型',
    `mat_cost` decimal(18,2) DEFAULT NULL COMMENT '物料成本',
    `proc_cost` decimal(18,2) DEFAULT NULL COMMENT '工艺成本',
    `gross_margin` decimal(18,2) DEFAULT NULL COMMENT '毛利',
    `tax_fee` decimal(18,2) DEFAULT NULL COMMENT '税费',
    `color_format` varchar(64) DEFAULT NULL COMMENT '色彩模式',
    `prod_attrs` longtext COMMENT '产品属性',
    `snapshot` longtext COMMENT '来源快照',
    PRIMARY KEY (`id`),
    KEY `idx_brt_sales_order_items_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单明细(来源 order_items)';

-- brt_sales_order_packages 订单包裹表（拆分 brt_sales_order_details 的包裹信息）
CREATE TABLE IF NOT EXISTS `brt_sales_order_packages` (
    `id` bigint NOT NULL COMMENT '来源包裹ID',
    `order_id` varchar(64) NOT NULL COMMENT '销售订单ID',
    `package_name` varchar(128) DEFAULT NULL COMMENT '包裹名称',
    `consignee` varchar(128) DEFAULT NULL COMMENT '收货人',
    `address` varchar(255) DEFAULT NULL COMMENT '收货地址',
    `tel` varchar(32) DEFAULT NULL COMMENT '收货电话',
    `orderItem_sns` longtext COMMENT '关联明细流水号集合',
    `counts` longtext COMMENT '明细数量集合',
    `addr_id` varchar(64) DEFAULT NULL COMMENT '地址ID',
    `shipping_fee` decimal(18,2) DEFAULT NULL COMMENT '运费',
    `delivery_net` varchar(128) DEFAULT NULL COMMENT '物流网点',
    `snapshot` longtext COMMENT '来源快照',
    PRIMARY KEY (`id`),
    KEY `idx_brt_sales_order_packages_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单包裹(来源 order_packages)';

-- brt_sales_order_item_procs 订单工艺表（由 order_items.component 拆解）
CREATE TABLE IF NOT EXISTS `brt_sales_order_item_procs` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_id` varchar(64) NOT NULL COMMENT '销售订单ID',
    `order_item_id` bigint NOT NULL COMMENT '订单明细ID',
    `proc_code` varchar(64) DEFAULT NULL COMMENT '工艺编码',
    `proc_name` varchar(255) DEFAULT NULL COMMENT '工艺名称',
    `proc_description` longtext COMMENT '工艺描述(JSON)',
    `accessory_code` varchar(64) DEFAULT NULL COMMENT '辅材编码',
    `accessory_number` decimal(18,2) DEFAULT NULL COMMENT '辅材数量',
    `proc_attach_path` longtext COMMENT '工艺附件路径',
    `proc_sort` int DEFAULT NULL COMMENT '工艺顺序',
    `snapshot` longtext COMMENT '来源快照',
    PRIMARY KEY (`id`),
    KEY `idx_brt_sales_order_item_procs_order_id` (`order_id`),
    KEY `idx_brt_sales_order_item_procs_item_id` (`order_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单工艺(来源 order_items.component)';
